/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_EspaceAdmin (void);
GtkWidget* create_AjoutUtilisateur (void);
GtkWidget* create_Modifier (void);
GtkWidget* create_Supprimer (void);
GtkWidget* create_database_utilisateurs (void);
GtkWidget* create_database_e (void);
GtkWidget* create_window_taches (void);
GtkWidget* create_Gestion_foyer (void);
GtkWidget* create_gestionw (void);
GtkWidget* create_accueilw (void);
GtkWidget* create_dialog_service_partie_2 (void);
GtkWidget* create_Accueil (void);
GtkWidget* create_addCap (void);
GtkWidget* create_editCap (void);
GtkWidget* create_listCap (void);
GtkWidget* create_delCap (void);
GtkWidget* create_defCap (void);
GtkWidget* create_ficheVal (void);
GtkWidget* create_anas (void);
GtkWidget* create_Ajouter_produit (void);
GtkWidget* create_Modifier_produit (void);
GtkWidget* create_Supprimer_produit (void);
GtkWidget* create_Affichage_produit (void);
GtkWidget* create_Repture_Stock (void);
GtkWidget* create_page_d_accueil (void);
GtkWidget* create_ajouterb (void);
GtkWidget* create_modifierb (void);
GtkWidget* create_supprimerb (void);
GtkWidget* create_dechetsb (void);
GtkWidget* create_chercherb (void);
GtkWidget* create_meilleur_menu (void);
GtkWidget* create_window_login (void);
